version: '3.9'
services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    image: custom-mariadb
    secrets:
      - db_password
      - db_root_password
    environment:
      MYSQL_DATABASE: ${SQLNAME}
      MYSQL_USER: ${SQLUSER}
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - inception_network
    restart: always

  wordpress:
    container_name: wp-php
    depends_on:
      - mariadb
    build: ./requirements/wordpress/.
    image: custom-wordpress
    secrets:
      - db_password
      - wp_credentials
    environment:
      WORDPRESS_DB_HOST: ${SQLHOST}
      WORDPRESS_DB_NAME: ${SQLNAME}
      WORDPRESS_DB_USER: ${SQLUSER}
      DOMAIN: ${DOMAIN}
      WPTITLE: ${WPTITLE}
      WPADMINUSER: ${WPADMINUSER}
      WPADMINEMAIL: ${WPADMINEMAIL}
      WPUSER: ${WPUSER}
      WPUSEREMAIL: ${WPUSEREMAIL}
      WPTHEME: ${WPTHEME}
    volumes:
      - wp-data:/var/www/html
    networks:
      - inception_network
    restart: always

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: ./requirements/nginx/.
    image: custom-nginx
    ports:
      - "443:443"
    volumes:
      - wp-data:/var/www/html
    networks:
      - inception_network
    environment:
      DOMAIN: ${DOMAIN}
    restart: always

volumes:
  wp-data:
    driver_opts:
      type: none
      o: bind
      device: /home/yadereve/data/wp-data/
  mariadb-data:
    driver_opts:
      type: none
      o: bind
      device: /home/yadereve/data/mariadb-data/

networks:
  inception_network:
    driver: bridge

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt
  wp_credentials:
    file: ./secrets/credentials.txt
